"""initial schema

Revision ID: af8271e32978
Revises: 
Create Date: 2026-09-27 23:20:29.205193

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af8271e32978'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the initial schema: 7 tables, their indexes, and their constraints.

    Alembic wrote the first draft of this body into the docstring as well as into
    the function body, so `upgrade()` carried two identical copies of the schema and
    the executable one was easy to miss. The duplicate is gone; this is the copy
    that runs.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Enum('SCAN_RUN', 'FINDING_CREATED', 'FINDING_UPDATED', 'FINDING_STATUS_CHANGED', 'FINDING_REOPENED', 'TICKET_CREATED', 'TICKET_UPDATED', 'REMEDIATION_PROPOSED', 'REMEDIATION_REVISED', 'REMEDIATION_REJECTED', 'REMEDIATION_ESCALATED', 'PULL_REQUEST_DRAFTED', 'PULL_REQUEST_APPROVED', 'PULL_REQUEST_REJECTED', 'AUTO_MERGE_BLOCKED', 'MCP_TOOL_INVOKED', name='audit_action', native_enum=False, length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=120), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('findings',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('UNSPECIFIED', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Enum('UNSPECIFIED', 'LOW', 'MEDIUM', 'HIGH', name='confidence', native_enum=False, length=32), nullable=False),
    sa.Column('scanner_kind', sa.Enum('UNSPECIFIED', 'FIXTURE', 'SEMGREP', 'ZAP', 'DEPENDENCY', name='scanner_kind', native_enum=False, length=32), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('cwe_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cve_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'TRIAGED', 'IN_PROGRESS', 'PROPOSED', 'AWAITING_REVIEW', 'REMEDIATED', 'ACCEPTED_RISK', 'FALSE_POSITIVE', name='finding_status', native_enum=False, length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remediated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remediation_attempts', sa.Integer(), nullable=False),
    sa.Column('auto_remediation_eligible', sa.Boolean(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_findings_fingerprint'))
    )
    op.create_index('ix_findings_cve_ids', 'findings', ['cve_ids'], unique=False, postgresql_using='gin')
    op.create_index('ix_findings_scanner_target', 'findings', ['scanner_kind', 'target'], unique=False)
    op.create_index('ix_findings_sla_due_at', 'findings', ['sla_due_at'], unique=False)
    op.create_index('ix_findings_status_severity', 'findings', ['status', 'severity'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ANALYST', 'APPROVER', 'ADMIN', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('remediation_proposals',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('DRAFTING', 'UNDER_REVIEW', 'REVISION_REQUESTED', 'APPROVED', 'REJECTED', 'ESCALATED', 'SUPERSEDED', name='proposal_status', native_enum=False, length=32), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('original_snippet', sa.Text(), nullable=False),
    sa.Column('final_patch', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('rounds_completed', sa.Integer(), nullable=False),
    sa.Column('reviewer_feedback', sa.JSON(), nullable=False),
    sa.Column('escalated_reason', sa.Text(), nullable=True),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_remediation_proposals_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remediation_proposals'))
    )
    op.create_index(op.f('ix_remediation_proposals_finding_id'), 'remediation_proposals', ['finding_id'], unique=False)
    op.create_index('ix_remediation_proposals_status', 'remediation_proposals', ['status'], unique=False)
    op.create_table('tickets',
    sa.Column('ticket_key', sa.String(length=32), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'BLOCKED', 'RESOLVED', 'CLOSED', name='ticket_status', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('UNSPECIFIED', 'CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='ticket_priority', native_enum=False, length=32), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_tickets_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('ticket_key', name=op.f('uq_tickets_ticket_key'))
    )
    op.create_index(op.f('ix_tickets_finding_id'), 'tickets', ['finding_id'], unique=False)
    op.create_index('ix_tickets_status_priority', 'tickets', ['status', 'priority'], unique=False)
    op.create_table('agent_runs',
    sa.Column('proposal_id', sa.Uuid(), nullable=True),
    sa.Column('finding_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('DEVELOPER', 'REVIEWER', 'SYSTEM', 'HUMAN', name='agent_role', native_enum=False, length=32), nullable=False),
    sa.Column('round_index', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('PROPOSE', 'REQUEST_CHANGES', 'APPROVE', 'REJECT', 'ESCALATE', 'ACCEPT', 'WITHDRAW', name='agent_decision', native_enum=False, length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('correlation_id', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['remediation_proposals.id'], name=op.f('fk_agent_runs_proposal_id_remediation_proposals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_runs_finding_created', 'agent_runs', ['finding_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_finding_id'), 'agent_runs', ['finding_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_proposal_id'), 'agent_runs', ['proposal_id'], unique=False)
    op.create_index('ix_agent_runs_proposal_round', 'agent_runs', ['proposal_id', 'round_index'], unique=False)
    op.create_table('pull_requests',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('base_branch', sa.String(length=255), nullable=False),
    sa.Column('target_repo', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'MERGED', 'CLOSED', name='pull_request_status', native_enum=False, length=32), nullable=False),
    sa.Column('diff_url', sa.String(length=1000), nullable=True),
    sa.Column('auto_merge_blocked', sa.Boolean(), nullable=False),
    sa.Column('human_approver', sa.String(length=255), nullable=True),
    sa.Column('human_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.String(length=255), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['remediation_proposals.id'], name=op.f('fk_pull_requests_proposal_id_remediation_proposals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pull_requests')),
    sa.UniqueConstraint('number', name=op.f('uq_pull_requests_number')),
    sa.UniqueConstraint('proposal_id', name=op.f('uq_pull_requests_proposal_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the change.

    Written out in full even when it is lossy, and the loss is called out in a
    comment. A downgrade that quietly drops data is a decision; a downgrade that
    is `pass` and silently leaves the schema ahead of the code is a bug.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pull_requests')
    op.drop_index('ix_agent_runs_proposal_round', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_proposal_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_finding_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_finding_created', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_tickets_status_priority', table_name='tickets')
    op.drop_index(op.f('ix_tickets_finding_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index('ix_remediation_proposals_status', table_name='remediation_proposals')
    op.drop_index(op.f('ix_remediation_proposals_finding_id'), table_name='remediation_proposals')
    op.drop_table('remediation_proposals')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_findings_status_severity', table_name='findings')
    op.drop_index('ix_findings_sla_due_at', table_name='findings')
    op.drop_index('ix_findings_scanner_target', table_name='findings')
    op.drop_index('ix_findings_cve_ids', table_name='findings', postgresql_using='gin')
    op.drop_table('findings')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
